# first, install Cypress, then run tests 
stages:
  - build
  - test

# to cache both npm modules and Cypress binary we use environment variables
# to point at the folders we can list as paths in "cache" job settings
variables:
  npm_config_cache: "$CI_PROJECT_DIR/.npm"
  CYPRESS_CACHE_FOLDER: "$CI_PROJECT_DIR/cache/Cypress"

# cache using branch name
# https://gitlab.com/help/ci/caching/index.md
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - .npm
    - cache/Cypress
    - node_modules

# this job installs NPM dependencies and Cypress
install:
  image: cypress/base:10
  stage: build

  script:
    - npm ci
    # check Cypress binary path and cached versions
    # useful to make sure we are not carrying around old versions
    - npx cypress cache path
    - npx cypress cache list
    #- $(npm bin)/print-env CI
    #- npm run cy:verify

# all jobs that actually run tests can use the same definition
run-cypress-tests:
  image: cypress/base:10
  stage: test
  script:
    # print CI environment variables for reference
    #- $(npm bin)/print-env CI
    # start the server in the background
    - npm run serve &
    # run Cypress test in load balancing mode
    - npx cypress run
  artifacts:
    when: on_failure
    paths:
      - /builds/whippet71/PaediatricDiabetesApp/cypress/videos/**/*.mp4
      - /builds/whippet71/PaediatricDiabetesApp/cypress/screenshots/**/*.png
    expire_in: 1 day

